# To run this check locally, install SkyWalking Eyes somehow
# (https://github.com/apache/skywalking-eyes). On macOS you can `brew install
# license-eye` and run `license-eye header check` or `license-eye header fix`.

name: license-check
on: pull_request
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check License Header
        uses: apache/skywalking-eyes/header@16b9726be37536a05279e061f0da02d205a2af77
