# To run this check locally, install SkyWalking Eyes somehow
# (https://github.com/apache/skywalking-eyes). On macOS you can `brew install
# license-eye` and run `license-eye header check` or `license-eye header fix`.

name: license-check
on: pull_request
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check License Header
        uses: apache/skywalking-eyes/header@315732dd4b8d3a015d8d9b91936b935a0b854817
