name: Run Generator

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Generate spec
        shell: bash
        run: |
          cd generator
          npm install
          npm run gen
