name: Update API Spec

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: api-spec-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-api-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
      - working-directory: "./oxide-openapi-gen-ts"
        run: 'npm ci'
      - run: ./tools/gen.sh
      - uses: EndBug/add-and-commit@645ecc0dd0a57f4d86d26c0aa5fc42c0a856fbca # v11.0.0
        with:
          add: .
          message: "Autogenerate config update"
          default_author: github_actions
